export default Liferay = {
	Language: {
		get: key => langKeys[key]
	},
	ThemeDisplay: {
		getUserName: () => 'brian.kim@liferay.com'
	}
}

const langKeys = {
	['about']: 'About',
	['account-history']: 'Account History',
	['account-owner']: 'Account Owner',
	['account-statistics']: 'Account Statistics',
	['account-phone']: 'Account Phone',
	['accounts']: 'Accounts',
	['account']: 'Account',
	['across-x-years']: 'Across {0} Years',
	['active']: 'Active',
	['active-subscriptions']: 'Active Subscriptions',
	['activity-timeline']: 'Activity Timeline',
	['address']: 'Address',
	['annual-recurring-revenue']: 'Annual Recurring Revenue',
	['annual-revenue']: 'Annual Revenue',
	['amount']: 'Amount',
	['api']: 'API',
	['assigned-to']: 'Assigned To',
	['associated-users']: 'Associated Users',
	['arr']: 'ARR',
	['bookings-in-the-last-12-months']: 'Bookings in the Last 12 Months',
	['by-x']: 'By {0}',
	['by-x-contacts']: 'By {0} Contacts',
	['calculated-discount-x']: 'Calculated Discount {0}',
	['close-lost']: 'Close Lost',
	['close-won']: 'Close Won',
	['closing-in-x']: 'Closing in {0}',
	['cms']: 'CMS',
	['comments']: 'Comments',
	['component']: 'Component',
	['contacts']: 'Contacts',
	['could-not-connect-to-the-server']: 'Could not connect to the server.',
	['converted-to-customer']: 'Converted to Customer',
	['created-x']: 'Created {0}',
	['crm']: 'CRM',
	['dashboard']: 'Dashboard',
	['data']: 'Data',
	['data-manager']: 'Data Manager',
	['date-created']: 'Date Created',
	['description']: 'Description',
	['details']: 'Details',
	['development']: 'Development',
	['discontinued']: 'Discontinued',
	['dossiera']: 'Dossiera',
	['email']: 'Email',
	['escalation']: 'Escalation',
	['existing-business']: 'Existing Business',
	['failed-to-parse-the-response']: 'Failed to parse the response.',
	['first-opportunity-close-won']: 'First Opportunity Close Won',
	['from-x']: 'From {0}',
	['id']: 'ID',
	['go-to-salesforce']: 'Go to Salesforce',
	['hide-details']: 'Hide Details',
	['hide-info']: 'Hide Info',
	['history']: 'History',
	['hosting']: 'Hosting',
	['identity-management']: 'Identity Management',
	['in-x']: 'In {0}',
	['inactive']: 'Inactive',
	['industry']: 'Industry',
	['integrated-technologies']: 'Integrated Technologies',
	['invalid-email-or-password']: 'Invalid email or password.',
	['last-modified']: 'Last Modified',
	['last-modified-x']: 'Last modified {0}.',
	['liferay-version']: 'Liferay Version',
	['lifetime-value']: 'Lifetime Value',
	['live']: 'Live',
	['load-more']: 'Load More',
	['login']: 'Login',
	['logout']: 'Logout',
	['login-successful']: 'Login successful!',
	['lost-opportunities']: 'Lost Opportunities',
	['minus-x']: '- {0}',
	['mobile-solution']: 'Mobile Solution',
	['more-info']: 'More Info',
	['name']: 'Name',
	['new-business']: 'New Business',
	['new-deal']: 'New Deal',
	['new-deals']: 'New Deals',
	['new-project']: 'New Project',
	['new-prospect']: 'New Prospect',
	['no-data']: 'No Data',
	['non-subscription']: 'Non-Subscription',
	['not-available']: 'N/A',
	['ok']: 'Ok',
	['open-opportunities']: 'Open Opportunities',
	['open-renewal']: 'Open Renewal',
	['open-tickets']: 'Open Tickets',
	['opportunities']: 'Opportunities',
	['opportunities-closed']: 'Opportunities Closed',
	['opportunity-owners']: 'Opportunity Owners',
	['other']: 'Other',
	['overview']: 'Overview',
	['owned-by-x']: 'Owned by {0}',
	['partner']: 'Partner',
	['partner-first-line-support']: 'Partner First Line Support',
	['password']: 'Password',
	['please-reauthenticate-to-continue']: 'Please re-authenticate to continue.',
	['please-try-again']: 'Please try Again',
	['preceding']: 'Preceding',
	['products']: 'Products',
	['professional-services']: 'Professional Services',
	['project-description']: 'Project Description',
	['project-details']: 'Project Details',
	['project-history']: 'Project History',
	['project-statistics']: 'Project Statistics',
	['projects']: 'Projects',
	['project']: 'Project',
	['qualified-lead']: 'Qualified Lead',
	['quarter-x']: 'Quarter {0}',
	['related-contact']: 'Related Contact',
	['renewal']: 'Renewal',
	['report']: 'Report',
	['search']: 'Search',
	['search-for-accounts']: 'Search for Accounts',
	['severity']: 'Severity',
	['show-details']: 'Show Details',
	['slash-x']: '/ {0}',
	['sold-by']: 'Sold By',
	['solution']: 'Solution',
	['something-blew-up']: 'Something blew up!',
	['something-went-wrong-while-trying-to-get-your-data']: 'Something went wrong while trying to get your data.',
	['sorry']: 'Sorry!',
	['sorry-your-session-has-expired']: 'Sorry, your session has expired.',
	['sorting-by-last-modified']: 'Sorting by Last Modified',
	['staging']: 'Staging',
	['start-of-x-x']: 'Start of {0} {1}',
	['status']: 'Status',
	['subscription-not-renewed']: 'Subscription Not Renewed',
	['subscription-renewed']: 'Subscription Renewed',
	['subscription-term']: 'Subscription Term',
	['support-language']: 'Support Language',
	['support-region']: 'Support Region',
	['there-are-no-active-subscriptions']: 'There are no active subscriptions.',
	['there-are-no-activities']: 'There are no activities.',
	['there-are-no-matching-accounts']: 'There are no matching accounts.',
	['there-are-no-opportunities']: 'There are no opportunities.',
	['there-are-no-projects']: 'There are no projects.',
	['there-is-no-data']: 'There is no data.',
	['this-activity-has-no-description']: 'This activity has no description.',
	['ticket-average-time-to-close']: 'Ticket Average Time to Close',
	['to-x']: 'To {0}',
	['to-x-contact']: 'To {0} Contact',
	['to-x-contacts']: 'To {0} Contacts',
	['today']: 'Today',
	['total-amount']: 'Total Amount',
	['training']: 'Training',
	['usd-x']: 'USD {0}',
	['users-total-concurrent']: 'Users (Total / Concurrent)',
	['view-all-x-owners']: 'View All {0} Owners',
	['x-active-accounts']: '{0} Active Accounts',
	['x-active-projects']: '{0} Active Projects',
	['x-accounts-of-x']: '{0} Accounts of {1}',
	['x-closed-lost-opportunities']: '{0} Closed Lost Opportunities',
	['x-closed-won-opportunities']: '{0} Closed Won Opportunities',
	['x-closing-on-x']: '{0} closing on {1}',
	['x-day']: '{0} Day',
	['x-days']: '{0} Days',
	['x-error-occured']: '{0} error occured.',
	['x-errors-occured']: '{0} errors occured.',
	['x-hubspot-activities']: '{0} Hubspot Activities',
	['x-hubspot-activity']: '{0} Hubspot Activity',
	['x-is-no-longer-maintained']: '{0} is no longer maintained.',
	['x-more-month']: '{0} More Month',
	['x-more-months']: '{0} More Months',
	['x-more-year']: '{0} More Year',
	['x-more-years']: '{0} More Years',
	['x-new-deals']: '{0} New Deals',
	['x-on-x']: '{0} on {1}',
	['x-open-opportunities']: '{0} Open Opportunities',
	['x-opportunities-in-progress']: '{0} Opportunities In Progress',
	['x-opportunity']: '{0} Opportunity',
	['x-x']: '{0} x',
	['x-/-x']: '{0} / {1}',
	['x-year-subscription']: '{0} Year Subscription'
}